# -*- coding: utf-8 -*-
"""bimt-page-rank-random-walk.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oiYSym3sPGMc-zks5CzR3_kbIVKHdtqN
"""

from random import random

from random import randint

PASSOS = 10000

A = [[0,0,.5,0,.5],
     [.5,0,.5,0,0],
     [0,.5,0,.5,0],
     [.5,0,0,0,.5],
     [0,0,1,0,0]]


#A = [[.02, 0.02, 0.88, 0.02, 0.02, 0.02, 0.02],
#     [0.02, 0.45, 0.45, 0.02, 0.02, 0.02, 0.02],
#     [0.31, 0.02, 0.31, 0.31, 0.02, 0.02, 0.02],
#     [0.02, 0.02, 0.02, 0.45, 0.45, 0.02, 0.02],
#     [0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.88],
#     [0.02, 0.02, 0.02, 0.02, 0.02, 0.45, 0.45],
#     [0.02, 0.02, 0.02, 0.31, 0.31, 0.02, 0.31]]

p = .86

n = len(A)

def pick_next(node,M=A,P=p):
  x = random()
  if x>P:
    #print("jump")
    return randint(0,n-1) #pula para um nó qualqura
  else: # pula para um nós que sai página
    total = M[node][0]
    for i in range(len(M[node])):
      y = random()
      if y <= total:
        return i
      total += A[node][i+1]
  print("hem?",x,i)

conta = [0]*n
node = 0

for i in range(PASSOS):
  conta[node] += 1
  node = pick_next(node)

conta2 = list(map(lambda x: x/PASSOS,conta))
total = sum(conta2)

print(total,conta2)


print("=====================================")

import numpy as np
from scipy.linalg import eig

Ar = np.array(A,float)


print(Ar)

e = np.ones((n,1),float)
et = e.transpose()
E = e*et/n
print(e,et,E)

# Matriz importante do Page Rank
PrM = p*Ar+(1-p)*E

print(PrM)

xv = e / n

# calcula o eigenvector esquerdo
w,vl,vr = eig(PrM,left=True)

print(vl[:,0]/sum(vl[:,0]))

print("=====================================")

xc = e / n
xct = et /n
PASSOSM = 400

for i in range(PASSOSM):
  xct = xct.dot(PrM)
  xct = xct/sum(sum(xct))



print(xct)

contagem = {}
for i in range(n):
  contagem[i] =  0

for i in range(1000000):
  contagem[randint(0,n-1)] += 1

